version: "3.8"
services:
  traefik:
    restart: unless-stopped
    ports:
      - "90:8080"

  api:
    restart: unless-stopped
    build:
      target: base
    volumes:
      - "./services/api/src:/app/src:ro"
    command: "sh ./wait-for-it.sh mongo:27017 redis:6379 kafka:9092 debezium:8083 -- yarn dev"

  mongo:
    restart: unless-stopped
    ports:
      - "27017:27017"

  redis:
    restart: unless-stopped
    ports:
      - "6379:6379"

  kafka:
    restart: unless-stopped
    ports:
      - "9092:9092"

  debezium:
    restart: unless-stopped
    ports:
     - "8083:8083"

  mongo-express:
    image: 'mongo-express:latest'
    hostname: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - '81:8081'

  redis-commander:
    image: 'rediscommander/redis-commander:latest'
    hostname: redis-commander
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - 'REDIS_HOSTS=local:redis:6379'
    ports:
      - '83:8081'

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    hostname: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - '84:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_URIS}