name: Publish

on:
  push:
    branches:
      - production

jobs:
  publish:
    environment: production
    runs-on: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Fetch secrets
        env:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}
        run: echo "$ENV_SECRETS" > env.json
      - name: Create service account for storage
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: echo "$GCP_SERVICE_ACCOUNT" > services/api/credentials.json
      - name: Install dependencies
        run: |
          sudo npm -g i pnpm@8
          pnpm install
      - name: Docker Build
        run: sudo make prod-build
      - name: Docker Stop Existing Run
        run: sudo make prod-stop
      - name: Docker Start
        run: sudo make prod-start-detach